#ifndef __RALINK_FLASH_H__
#define __RALINK_FLASH_H__

#if defined (CONFIG_RT2880_FLASH_32M)
	#define MTD_BOOT_PART_SIZE	0x40000
	#define	MTD_FACTORY_PART_SIZE	0x20000
	#define	MTD_SYSLOG_PART_SIZE	0x20000 // Make sure MTD_BOOT_PART_SIZE = MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE

	#define	MTD_CONFIG_PART_SIZE	0x20000
	#define	MTD_NVRAM_PART_SIZE	0x20000
#else
	#if defined (RECONFIG_PARTITION_SIZE)
		#if !defined (MTD_BOOT_PART_SIZE)
		#error "Please define MTD_BOOT_PART_SIZE"
		#endif
		#if !defined (MTD_CONFIG_PART_SIZE)
		#error "Please define MTD_CONFIG_PART_SIZE"
		#endif
		#if !defined (MTD_FACTORY_PART_SIZE)
		#error "Please define MTD_FACTORY_PART_SIZE"
		#endif
	#else
		#define MTD_BOOT_PART_SIZE	0x30000
		#define	MTD_FACTORY_PART_SIZE	0x10000
		#define	MTD_SYSLOG_PART_SIZE	0x20000 // Make sure MTD_BOOT_PART_SIZE = MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE

		#define	MTD_CONFIG_PART_SIZE	0x10000
		#define	MTD_NVRAM_PART_SIZE	0x20000
	#endif
#endif

#define MTD_KERN_PART_OFFSET	MTD_BOOT_PART_SIZE + MTD_CONFIG_PART_SIZE + MTD_FACTORY_PART_SIZE

#ifdef CONFIG_DUAL_IMAGE
	#if defined (CONFIG_RT2880_FLASH_4M)
	#define IMAGE1_SIZE		0x200000 - MTD_BOOT_PART_SIZE // or MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE
	#elif defined (CONFIG_RT2880_FLASH_8M)
	#define IMAGE1_SIZE		0x400000 - MTD_BOOT_PART_SIZE // or MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE
	#elif defined (CONFIG_RT2880_FLASH_16M)
	#define IMAGE1_SIZE		0x800000 - MTD_BOOT_PART_SIZE // or MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE
	#elif defined (CONFIG_RT2880_FLASH_32M)
	#define IMAGE1_SIZE		0x1000000 - MTD_BOOT_PART_SIZE // or MTD_FACTORY_PART_SIZE + MTD_SYSLOG_PART_SIZE
	#endif

	#define MTD_KERN2_PART_OFFSET	MTD_KERN_PART_OFFSET + IMAGE1_SIZE - (MTD_NVRAM_PART_SIZE + MTD_CONFIG_PART_SIZE)

#else // Non Dual Image
	#if defined (CONFIG_RT2880_FLASH_2M)
	#define IMAGE1_SIZE		0x200000 - IMAGE_OVERHEAD
	#elif defined (CONFIG_RT2880_FLASH_4M)
	#define IMAGE1_SIZE		0x400000 - IMAGE_OVERHEAD
	#elif defined (CONFIG_RT2880_FLASH_8M)
	#define IMAGE1_SIZE		0x800000 - IMAGE_OVERHEAD
	#elif defined (CONFIG_RT2880_FLASH_16M)
	#define IMAGE1_SIZE		0x1000000 - IMAGE_OVERHEAD
	#elif defined (CONFIG_RT2880_FLASH_32M)
	#define IMAGE1_SIZE		0x2000000 - IMAGE_OVERHEAD
	#else
	#define IMAGE1_SIZE		CONFIG_MTD_PHYSMAP_LEN - IMAGE_OVERHEAD
	#endif
#endif


#ifdef CONFIG_RT2880_ROOTFS_IN_FLASH
	#ifdef CONFIG_ROOTFS_IN_FLASH_NO_PADDING
		#define CONFIG_MTD_KERNEL_PART_SIZ 0
	#endif
	#define	MTD_KERN_PART_SIZE	CONFIG_MTD_KERNEL_PART_SIZ
	#define MTD_ROOTFS_PART_SIZE	IMAGE1_SIZE - (MTD_CONFIG_PART_SIZE + MTD_NVRAM_PART_SIZE + \
						+ MTD_KERN_PART_SIZE)
#else
	#define MTD_KERN_PART_SIZE	IMAGE1_SIZE - (MTD_CONFIG_PART_SIZE + MTD_NVRAM_PART_SIZE)
#endif

#define BOOT_FROM_NOR	0
#define BOOT_FROM_NAND	2
#define BOOT_FROM_SPI	3

int ra_check_flash_type(void);

#endif //__RALINK_FLASH_H__
